### ISSUE TITLE
Error handling - Error handling, "try..catch" 번역 희망합니다

### ISSUE THREAD

**Issue by kbpark** [Violet-Bora-Lee/javascript-tutorial-ko#5]
Error handling - Error handling, "try..catch" 번역 희망합니다.
kbpark.goodman@gmail.com

**Comment by Violet-Bora-Lee** [comment]
구글 시트 편집권한 드렸습니다. :)

**Comment by Violet-Bora-Lee** [comment]
번역이 완료되어 이슈 클로징하겠습니다.

**Comment by kbpark** [comment]
앗 사실 끝까지 번역 안 했었는데 방금 끝까지 번역해서 Pull Request 하였습니다.
