### ISSUE TITLE
1-js\02-first-steps\05-types\article.md 번역 희망

### ISSUE THREAD

**Issue by keehyun2** [Violet-Bora-Lee/javascript-tutorial-ko#8]
번역 희망합니다

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. gmail계정을 알려주시면 번역어와 대시보드를 수정하실 수 있는 권한을 드릴게요. 참여 감사합니다. :)

**Comment by keehyun2** [comment]
> 안녕하세요. gmail계정을 알려주시면 번역어와 대시보드를 수정하실 수 있는 권한을 드릴게요. 참여 감사합니다. :)

네~ 안녕하세요~:)
1-js\02-first-steps\05-types\article.md 번역 희망합니다. 
파일을 잘못 찾았네요 ㅠㅠ 
keehyun2@gmail.com 입니다.
